-- create table user (
--                         user_id bigserial not null,
--                         username varchar(255),
--                         primary key (user_id)
-- );
--
-- alter table if exists task
--     add constraint FK2hsytmxysatfvt0p1992cw449
--     foreign key (user_id) references "user";
